FROM node:16.14.0-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run ng build --prod

FROM nginx:1.21.3-alpine
COPY --from=builder /app/dist/hahn-softwareentwicklung /usr/share/nginx/html
EXPOSE 80
EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]
