FROM node:16.14.0-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --prod

FROM nginx:1.21.3-alpine
COPY --from=builder /app/dist/frontend /usr/share/nginx/html
EXPOSE 80